# Generated by Django 4.2.9 on 2026-09-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='solar_voltage',
            field=models.FloatField(default=0.0, help_text='Solar panel voltage in volts'),
        ),
    ]
